### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by MootoolsSoftware** [syoyo/tinyusdz#110]
Model: [crowd_crowd_arnoldExample.zip](https://github.com/syoyo/tinyusdz/files/13725807/crowd_crowd_arnoldExample.zip)

We encounter a problem with std::vector parsing this file on Windows:

File: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\include\vector
Line: 114
Expression: cannot seek vector iterator before begin

Here is the call stack
![image](https://github.com/syoyo/tinyusdz/assets/15813085/155cf46d-36fa-47ff-8df1-899885b75ed6)

It seems that some index are out of bounds.

**Comment by syoyo** [comment]
You should describe/provide reproducible procedure/code.

**Comment by MootoolsSoftware** [comment]
It can be reproduce simply using:

```tydra_to_renderscene.exe "crowd_crowd_arnoldExample_v001.usd"```

**Comment by syoyo** [comment]
Oh good find. 

Got success to reproduce and confirmed the issue.

I didn't realized MS STL throws error when accessing `vector begin() - 1`:  The situation happens when the `_samples.size() == 1` and `std::lower_bound` returns `it == _samples.begin()`
(FYI no out-of-bounds issue on Linux(libcxx))

 https://github.com/syoyo/tinyusdz/blob/21901f7805c4f4ad7f5217ba64e0e573399da3c2/src/prim-types.hh#L1154

Now the issue is fixed in the `dev` branch.

**Comment by MootoolsSoftware** [comment]
Thanks for the fast solution!
