### ISSUE TITLE
API design improvements: no way to initialize a Stage struct

### ISSUE THREAD

**Issue by MootoolsSoftware** [syoyo/tinyusdz#111]
The method RenderSceneConverter::ConvertMaterial is a public method and require a stage to be used.

```
bool RenderSceneConverter::ConvertMaterial(const Path &mat_abs_path,
                                           const tinyusdz::Material &material,
                                           RenderMaterial *rmat_out) {
  if (!_stage) {
    PUSH_ERROR_AND_RETURN("stage is nullptr.");
  }
```

The only way to assign a stage to the RenderSceneConverter is through RenderSceneConverter::ConvertToRenderScene.

It would be nice to either

* be able to assign a stage to RenderSceneConverter and use RenderSceneConverter::ConvertMaterial independently of RenderSceneConverter::ConvertToRenderScene.
* have a protected access for RenderSceneConverter::ConvertMaterial is such operation is not possible.

**Comment by syoyo** [comment]
Thanks. Current API design of RenderSceneConverter is nasty. 

I'll try to improve it by supplying `Stage` instance to RenderSceneConverter constructor, since `Stage` instance must be preserved during ConvertMesh, ConvertMaterial, ConvertUVTexture, etc.  I want to keep ConvertMaterial(and others) public, because I think people sometime want to convert Material(and others) only.

**Comment by syoyo** [comment]
I have introduced `RenderSceneConverterEnv` and `Stage` instance is preserved in this environment, and this env is used for ConvertMesh, ConvertMaterial, ...

https://github.com/syoyo/tinyusdz/blob/bc9f46cc815353adbc86431d9f55c386ea5881b7/examples/tydra_to_renderscene/to-renderscene-main.cc#L177
