### ISSUE TITLE
GPrim: consistency of "props" vs. "displayColor"

### ISSUE THREAD

**Issue by fynv** [syoyo/tinyusdz#23]
In one occasion, I can't read value from "displayColor", but found it in props["primvars:displayColor"].
Is this the expected behavior?  What's the difference between displayColor and props["primvars:displayColor"]?

**Comment by syoyo** [comment]
https://github.com/PixarAnimationStudios/USD/blob/3abc46452b1271df7650e9948fef9f0ce602e3b2/pxr/usd/usdGeom/schema.usda#L601

Its an expected behavior. attributes with 'primvars' namespace and other custom attributes(not declared in the schema) are stored in 'props'

Do you have a USD scene with 'displayColor' solely?

**Comment by fynv** [comment]
I haven't seen one without "primvars" yet.

At line 55, usdGeom.hh, the comment says: "primvars:displayColor". 
That looks confusing to me, because that is exactly the way the attribute appears in the USDA.

**Comment by syoyo** [comment]
> At line 55, usdGeom.hh, the comment says: "primvars:displayColor".

Good catch. Oops, I forget to delete this line... Will be deleted in next commit. 

BTW, I found `custom displayColor` use in `Material`, not `GPrim` though: https://github.com/PixarAnimationStudios/USD/blob/release/pxr/usdImaging/usdImagingGL/testenv/testUsdImagingGLShadeMaterial/coloredCubes.usda#L58

**Comment by fynv** [comment]
Great, thanks!
Closing.

**Comment by syoyo** [comment]
FYI removed member variables in this commit: https://github.com/syoyo/tinyusdz/commit/a91321386f942d6663a7b25bed5d95ea6047c0f5
